### ISSUE TITLE
Clicking anywhere in the terminal should select it

### ISSUE THREAD

**Issue by alexxgathp** [rohanchandra/javascript-terminal#7]
When you have an actual terminal clicking anywhere within it will have it ready to type into.

In your terminal simulator demo, you have to click where you are typing. Kind of annoying for someone that uses a terminal a lot.

**Comment by rohanchandra** [comment]
Since this library is just concerned with the terminal logic and not the UI, the demos here are just minimal examples of integrating javascript-terminal.

Check out my [react-terminal-component](https://github.com/rohanchandra/react-terminal-component) if you're looking for a production ready front-end UI for this library (recently, a contributor added a [clickToFocus prop](https://rohanchandra.gitlab.io/react-terminal-component/storybook/?selectedKind=ReactTerminal&selectedStory=with%20clickToFocus&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) which does what you're looking for).

**Comment by alexxgathp** [comment]
Oh I see, thank you for the clarification.

**Comment by briancanspit** [comment]
You can enclose the entire terminal inside a div with a class or id, then select it with jQuery (plain JavaScript will work as well) as below to ensure that the input field will be focused on upon click of any area of the terminal:

```
$(".yourTerminalClass").click(function(){
    $("#input").focus(); //the input field has the id "input"
});
```
