### ISSUE TITLE
Case sensitivity of commands and execution

### ISSUE THREAD

**Issue by alexxgathp** [rohanchandra/javascript-terminal#8]
I am using redux-saga and integrating that with the related project  react stateless terminal component.
When the stateless component hits enter / submit, it executes the command in the emulator.
https://github.com/rohanchandra/react-terminal-component/blob/29ea72b33fbcd72ab72c37068eb45e1a1cfef33f/src/ReactTerminalStateless.js#L45-L46

This is okay-  I have the commands respond blank and then my asynchronous redux-saga appends its output before saving the state.

However, my use case requires case insensitivity. The emulator command mappings and execution seem to be case-sensitive. So when I use a command where the case does not match, it outputs the error message (before my appended output). "Command not found"

Maybe a flag or argument should be created for case insensitive execution? I suppose it could be done by defaulting to lower case version or upper case version of whatever is passed. Then, documenting  which case to use to have case insensitivity.

**Comment by rohanchandra** [comment]
I don't think the emulator should be modified directly as case insensitivity non-standard behavior.

Instead `ReactTerminalStateless.js` from `react-terminal-component`, should accept a emulator instance as an argument instead of directly creating an emulator with `this.emulator = new Emulator();` (like what I've done with `emulatorState`).

That way you could should be able to pass in a wrapped emulator that does the custom logic you need.

Here's a pseduocode example:

```javascript
export default class WrappedEmulator {

    constructor() {
        // Create instance of the emulator from javascript-terminal
        this._emulator = Emulator();
    }

    autocomplete(state, partialStr) {
        return _emulator(state, partialStr);
    };

    suggest(state, partialStr) {
        return _emulator(state, partialStr);
    };

    execute(state, str, executionListeners = []) {
        // pseudo code
        extract terminal command name from str
        terminal command name to lowercase
        return _emulator(state, str, executionListeners);
    };
}
```

**Comment by rohanchandra** [comment]
I don't think the emulator should be modified directly as case insensitivity is non-standard behavior for a terminal.

Instead `ReactTerminalStateless.js` from `react-terminal-component`, can be modified to accept a emulator instance as an argument, instead of directly creating an emulator with `this.emulator = new Emulator();` (like what I've done with `emulatorState`).

That way you could should be able to pass in a wrapped emulator that has the custom logic you need.

Here's a pseduocode example:

```javascript
export default class WrappedEmulator {

    constructor() {
        // Create instance of the emulator from javascript-terminal
        this._emulator = Emulator();
    }

    autocomplete(state, partialStr) {
        return _emulator(state, partialStr);
    };

    suggest(state, partialStr) {
        return _emulator(state, partialStr);
    };

    execute(state, str, executionListeners = []) {
        // pseudo code
        extract terminal command name from str
        terminal command name to lowercase
        return _emulator(state, str, executionListeners);
    };
}
```
